name: Run MansheAI Review
jobs:
review:
  runs-on: ubuntu-latest

  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run MansheAI Review
      uses: AlmaCRH/mansheai-action@v1
      with:
        ai_key: ${{ secrets.CODESTRAL_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
